development:
  adapter: postgresql
  database: photo-development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: photo-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: photo-test
  pool: 5
  timeout: 5000
